apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-initcontainer
  namespace: zz
  labels:
    app: zz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zz-app
  template:
    metadata:
      name: zz-app
      labels:
        app: zz-app
    spec:
      volumes:
      - name: zz-data-emptydir
        emptyDir:
          sizeLimit: 500Mi
      initContainers:
      - name: init-touch
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zz-data-emptydir
          mountPath: /myshare
        command:
        - sh
        - -c
        - |-
          #!/bin/sh
          touch /myshare/test.txt
          echo 123 >> /myshare/test.txt
      - name: echo
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - for i in `seq 1 10`; do echo $i; sleep 1; done
      restartPolicy: Always
      containers:
      - name: hello
        image: registry.cn-hangzhou.aliyuncs.com/zzimage/zz-hello:v1.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zz-data-emptydir
          mountPath: /myshare
        startupProbe:
          httpGet:
            path: /health
            port: 12000
          initialDelaySeconds: 0     # 容器启动后多久开始探测
          timeoutSeconds: 4          # 表示容器必须在timeoutSeconds秒内做出相应反馈给probe，否则视为探测失败
          periodSeconds: 3           # 探测周期，每periodSeconds秒探测一次
          failureThreshold: 30       # 连续探测failureThreshold次失败表示失败
        livenessProbe:
          httpGet:
            path: /health
            port: 12000
          initialDelaySeconds: 0    # 容器启动后多久开始探测
          timeoutSeconds: 4          # 表示容器必须在timeoutSeconds秒内做出相应反馈给probe，否则视为探测失败
          periodSeconds: 10          # 探测周期，每periodSeconds秒探测一次
          failureThreshold: 3        # 连续探测failureThreshold次失败表示失败
        readinessProbe:
          httpGet:
            path: /health
            port: 12000
          initialDelaySeconds: 0    # 容器启动后多久开始探测
          timeoutSeconds: 4          # 表示容器必须在timeoutSeconds秒内做出相应反馈给probe，否则视为探测失败
          periodSeconds: 10          # 探测周期，每periodSeconds秒探测一次
          successThreshold: 2        # 连续探测successThreshold次成功表示成功
          failureThreshold: 3        # 连续探测failureThreshold次失败表示失败