---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-my-nginx
  namespace: zz
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: svc-my-nginx
  namespace: zz
spec:
  selector:
   app: my-nginx
  type: ClusterIP
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80