apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nfs
  namespace: zzns
  labels:
    app: zz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zz-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: zz-app
      labels:
        app: zz-app
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: zz-harbor
      volumes:
      - name: zz-nfs
        nfs:
          server: zz.nfs.com
          path: /data/volumes
      containers:
      - name: zz-write
        image: zz.harbor.com/zz-public/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
        volumeMounts:
        - name: zz-nfs
          mountPath: /data/volumes
