apiVersion: apps/v1
kind: Deployment
metadata:
  name: zz-hello-deploy-rollingupdate
  namespace: zzns
  labels:
    app: zz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zz-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: zz-app
      labels:
        app: zz-app
    spec:
      containers:
      - name: hello
        image: zz.harbor.com/zz/zz-hello:v1.0.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: zz-harbor
      
