apiVersion: v1
kind: PersistentVolume
metadata:
  name: zz-pv-nfs-002
  labels:
    name: zz-pv-nfs-002
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    path: /data/v2
    server: zz.nfs.com
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: zz-nfs-sc
  capacity:
    storage: "2Gi"