apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: zz
  labels:
    tier: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: proxy
  template:
    metadata:
      name: nginx
      labels:
        tier: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80