---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: zz
spec:
  externalTrafficPolicy: Cluster
  selector:
   app: my-nginx
  type: NodePort
  ports:
  - name: admin-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-my-nginx
  namespace: zz
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
      restartPolicy: Always