---
apiVersion: v1
kind: Service
metadata:
  name: svc-loadBalancer
  namespace: zz
spec:
  selector:
    app: my-nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  clusterIP: 10.0.171.239
  loadBalancerIP: 78.11.24.19
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-my-nginx
  namespace: zz
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
      restartPolicy: Always