apiVersion: v1
kind: PersistentVolume
metadata:
  name: zz-pv-nfs-001
  labels:
    name: zz-pv-nfs-001
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    path: /data/v1
    server: zz.nfs.com
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: zz-nfs-sc
  capacity:
    storage: "2Gi"