apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zz-pvc-001
  namespace: zzns
spec:
  resources:
    requests:
      storage: "2Gi"
  accessModes: ["ReadWriteMany"]
  storageClassName: zz-nfs-sc
  volumeMode: Filesystem