---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: zz-redis
spec:
  selector:
    app: redis
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-access
  namespace: zz-redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 32001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: zz-redis
  labels:
    app: redis
spec:
  replicas: 4
  serviceName: redis-headless
  selector:
    matchLabels:
      app: redis
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      storageClassName: managed-nfs-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      restartPolicy: Always
      volumes:
      - name: redis-conf
        configMap:
          name: zz-redis
          items:
          - key: redis-conf
            path: redis-conf
      - name: redis-secret
        secret:
          secretName: zz-redis
          items:
          - key: password
            path: password
      - name: redis-config
        emptyDir: {}
      initContainers:
      - name: redis-init
        image: docker.m.daocloud.io/redis/redis-stack-server:latest
        command:
        - bash
        - -c
        - |-
          #!/usr/bin/env bash
          # chmod +x /tmp/redis/init-redis.sh
          # source /tmp/redis/init-redis.sh
          echo "复制redis.con到指定位置(不同镜像，位置不同)"
          cp /tmp/redis/conf/redis-conf /etc/redis/redis.conf
          REDIS_PASSWORD=$(cat /tmp/redis/secret/password)
          echo "修改一些公共参数"
          cat >> /etc/redis/redis.conf <<EOF

          port 6379
          bind 0.0.0.0
          dbfilename dump.rdb
          dir /data
          appendonly yes
          appendfilename "appendonly.aof"
          requirepass $REDIS_PASSWORD
          EOF
          if [ "$(redis-cli -h sentinel -p 26379 ping)" != "PONG" ]; then
              echo "Sentinel 没有找到 master, 默认设置 redis-0 为master"
              if [ "$(hostname)" = "redis-0" ]; then
                  echo "主节点是redis-0, 不需要修改配置"
              else
                  echo "其他节点认为是slave, 修改redis.conf开启复制"
                  # 获取master 全域名 redis-0.redis-headless.zz-redis.svc.cluster.local
                  MASTER_FDQN=`hostname -f | sed -e 's/redis-[0-9]\./redis-0./'`
                  cat >> /etc/redis/redis.conf <<EOF

          masterauth $REDIS_PASSWORD
          replicaof $MASTER_FDQN 6379
          EOF
              fi
          else
              echo "Sentinel 找到了 master"
              MASTER="$(redis-cli -h sentinel -p 26379 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
              echo "Master got: $MASTER, updating this in redis.conf"
              echo -e "\nreplicaof $MASTER 6379" >> /etc/redis/redis.conf
          fi
          cat /etc/redis/redis.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: redis-conf
          mountPath: /tmp/redis/conf
        - name: redis-secret
          mountPath: /tmp/redis/secret
      containers:
      - name: redis
        image: docker.m.daocloud.io/redis/redis-stack-server:latest
        imagePullPolicy: IfNotPresent
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: redis-data
          mountPath: /data
          subPath: data