apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: zz
spec:
  externalTrafficPolicy: Cluster
  selector:
   app: zz
  type: NodePort
  ports:
  - name: admin-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010 # 30000-32767, 虚拟端口
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009