apiVersion: v1
kind: Service
metadata:
  name: zz-service-nodeport
  namespace: zzns
spec:
  externalTrafficPolicy: Cluster
  selector:
   app: zz-app
  ports:
  - name: admin-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010 # 30000-32767, 虚拟端口
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
  type: NodePort