apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorization-role-binding
  namespace: zz
subjects:
  - kind: ServiceAccount
    name: zz-sa
    namespace: zz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zz-role
  