---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image-secret
  namespace: zz
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  serviceAccountName: default
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
    spec:
      restartPolicy: Always
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']