---
apiVersion: v1
kind: Secret
metadata:
  name: secret-volume
  namespace: zz
immutable: false
type: Opaque
data:
  username: enoK
  password: MTIzNDU2Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secret-volume
  namespace: zz
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
    spec:
      restartPolicy: Always
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-volume
          items:
          - key: username
            path: username
          - key: password
            path: password
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
        volumeMounts:
        - name: secret-volume
          mountPath: "/tmp"