apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false" # 设置为"false"时删除PVC不会保留数据,"true"则保留数据
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
  onDelete: delete
mountOptions:
  - hard # 指定为硬挂载方式
  - nfsvers=4 # 指定NFS版本,这个需要根据NFS Server版本号设置