apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-recreate
  namespace: zz
  labels:
    app: zz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zz-app
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: zz-app
      labels:
        app: zz-app
    spec:
      restartPolicy: Always
      containers:
      - name: hello
        image: registry.cn-hangzhou.aliyuncs.com/zzimage/zz-hello:v1.0.0
        imagePullPolicy: IfNotPresent