apiVersion: v1
kind: PersistentVolume
metadata:
  name: zz-pv-nfs-001
  namespace: zzns
  labels:
    name: zz-pv-nfs-001
spec:
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/v1
    server: zz.nfs.com
  accessModes: ["ReadWriteMany"]
  storageClassName: zz-nfs-sc
  capacity:
    storage: "2Gi"