apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zz-cluster-role
  namespace: zz
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "endpoints", "nodes", "secrets", "namespaces"]
    verbs: ["get","watch","list","update"]