---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis1
  namespace: zz-redis
  labels:
    name: zz-redis
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    path: /data/redis1
    server: zz.nfs.com
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: zz-nfs-sc
  capacity:
    storage: "2Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zz-redis2
  labels:
    name: zz-redis
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    path: /data/redis2
    server: zz.nfs.com
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: zz-nfs-sc
  capacity:
    storage: "2Gi"