apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: zz-redis
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  resources:
    requests:
      storage: "500Mi"
  accessModes: ["ReadWriteMany"]